### ISSUE TITLE
Add Orientation to TagKeys

### ISSUE THREAD

**Issue by LandonSchropp** [mliebelt/pgn-types#3]
The Lichess API now accepts an `orientation` parameter for the study API, which includes an `Orientation` tag in the resulting PGN. It would be great if the `TagKeys` type could be updated to include `Orientation`.

**Comment by mliebelt** [comment]
Sorry for re-opening it, but it is not at all clear when that orientation tag can be used, and what the values are. 

I was looking at https://lichess.org/api#tag/Studies, found there the string "orientation", which said:

> orientation | booleanDefault: false
> Add a Orientation PGN tag with the chapter predefined orientation.
> Example: [Orientation "white"]

Can you tell me where the tag "Orientation" could then be seen anywhere? When I use the UI, and export a chapter, there is no Orientation tag visible.

So I tried myself, what the result is. `curl https://lichess.org/api/study/<STUDY_ID>/<CHAPTER_ID>.pgn\?orientation\=true` gave me

* ... [Orientation "black"]
* or ... [Orientation "white"]

Very unusual to have an additional PGN tag for that, but anyhow.

**Comment by LandonSchropp** [comment]
The primary use of this tag is to determine which way the board is oriented toward when creating a study. For example, you could create a study of the Italian Opening from white's perspective, or you could create a study of playing _against_ the study from black's perspective.

This is information that's stored along with the study, but previously wasn't exposed in the API. In my particular use case, I'm using the study information to build an interactive application that lets you practice moves in a given study, but that's only possible if I know the orientation the original study was created in.

I believe the tag was added to the PGN because there wasn't any other way of returning this information since the API only returns a PGN.

Does that make sense?

**Comment by mliebelt** [comment]
Sounds reasonable. My point here is that PGN was invented (and used) to represent the games played at some point in time. But yes, having the orientation defined is helpful in some use cases, not really part of the PGN spec. But that is easier than define another spec (additionally) to represent useful information for playing games.
